"""add witness columns to all tables

Revision ID: 70c7c6800337
Revises: ebe0f1588ef0
Create Date: 2026-04-08 11:08:42.327652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c7c6800337'
down_revision = 'ebe0f1588ef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('births', schema=None) as batch_op:
        batch_op.add_column(sa.Column('witness1_relation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('witness2_relation', sa.Text(), nullable=True))

    with op.batch_alter_table('citizen_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ref_certificate_number', sa.Text(), nullable=True))

    with op.batch_alter_table('deaths', schema=None) as batch_op:
        batch_op.add_column(sa.Column('witness1_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('witness1_id', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('witness1_relation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('witness2_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('witness2_id', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('witness2_relation', sa.Text(), nullable=True))

    with op.batch_alter_table('divorces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('witness1_relation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('witness2_relation', sa.Text(), nullable=True))

    with op.batch_alter_table('marriages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('witness1_relation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('witness2_relation', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nni'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('marriages', schema=None) as batch_op:
        batch_op.drop_column('witness2_relation')
        batch_op.drop_column('witness1_relation')

    with op.batch_alter_table('divorces', schema=None) as batch_op:
        batch_op.drop_column('witness2_relation')
        batch_op.drop_column('witness1_relation')

    with op.batch_alter_table('deaths', schema=None) as batch_op:
        batch_op.drop_column('witness2_relation')
        batch_op.drop_column('witness2_id')
        batch_op.drop_column('witness2_name')
        batch_op.drop_column('witness1_relation')
        batch_op.drop_column('witness1_id')
        batch_op.drop_column('witness1_name')

    with op.batch_alter_table('citizen_requests', schema=None) as batch_op:
        batch_op.drop_column('ref_certificate_number')

    with op.batch_alter_table('births', schema=None) as batch_op:
        batch_op.drop_column('witness2_relation')
        batch_op.drop_column('witness1_relation')

    # ### end Alembic commands ###
