"""Add witness columns to births

Revision ID: ebe0f1588ef0
Revises: 
Create Date: 2026-04-05 14:12:52.161075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe0f1588ef0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('births', schema=None) as batch_op:
        batch_op.add_column(sa.Column('witness1_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('witness1_id', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('witness2_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('witness2_id', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('births', schema=None) as batch_op:
        batch_op.drop_column('witness2_id')
        batch_op.drop_column('witness2_name')
        batch_op.drop_column('witness1_id')
        batch_op.drop_column('witness1_name')

    # ### end Alembic commands ###
